// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4iU5MUlHaif-KFMZZHA6FPxmC2nk9vp4',
    appId: '1:726525590326:android:d095da6e20b86367435197',
    messagingSenderId: '726525590326',
    projectId: 'fundimetwork',
    storageBucket: 'fundimetwork.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgXXqKFo_CbN-PCEBBIhodFNyBW7TrfOg',
    appId: '1:726525590326:ios:1e19a362b97a78ac435197',
    messagingSenderId: '726525590326',
    projectId: 'fundimetwork',
    storageBucket: 'fundimetwork.firebasestorage.app',
    iosBundleId: 'com.example.basefundi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzwVYh1U7sA1G94qOGIWQnmSti6zh7BBE',
    appId: '1:726525590326:web:2c831b249b3e8ea0435197',
    messagingSenderId: '726525590326',
    projectId: 'fundimetwork',
    authDomain: 'fundimetwork.firebaseapp.com',
    storageBucket: 'fundimetwork.firebasestorage.app',
  );
}
